trigger:
- main  # Change this if your branch is not 'main'

pool:
  name: Default  # This uses your self-hosted agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  displayName: 'Maven Build and Test'